name: Cypress Tests using Cypress Docker Image

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node18.12.0-chrome106-ff106
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress test run
        uses: cypress-io/github-action@v6
        with:
          build: npm run
          browser: chrome

      - name: Generate HTML report
        run: npm run report:generate
        if: always()
      # - name: Prepare reports
      #   if: always()
      #   run: |
      #       cd frontend
      #       npm i -g mochawesome-merge
      #       npm i -g mochawesome-report-generator
      #       mochawesome-merge test/cypress/reports/mocha/*.json > ./test/cypress/reports/mocha/index.json
      #       marge --charts=true --showPassed=false -o ./test/cypress/reports/mocha/ ./test/cypress/reports/mocha/index.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/html
        if: always()
