name: Cypress Test

on:
  push:
    branches:
      - main # Replace with your desired branch

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Change this to your desired Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build the Application
        run: npm run build

      - name: Start the Application
        run:
          npm start
          # This runs the npm start command in the background

      - name: Wait for the Application to Start
        run: sleep 10 # Adjust the sleep duration as needed to ensure the application is running

      - name: Run Cypress Tests
        run: npx cypress run --browser chrome
