name: Cypress Test
on: push
   #branches:
    # - main
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Cypress Run
       uses: actions/checkout@v2
       with:
        build: npm run build
        start: npm start
        browser: chrome
   
        
